change ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -387,53 +387,53 @@ jobs:
       - name: Check Test Binary
         run: ${{ matrix.binary-check }} tests/compiler/534.lean.out
         if: ${{ !matrix.cross && needs.configure.outputs.quick == 'false' }}
-      - name: Build Stage 2
-        run: |
-          cd build
-          ulimit -c unlimited # coredumps
-          make -j4 stage2
-        if: matrix.test-speedcenter
-      - name: Check Stage 3
-        run: |
-          cd build
-          ulimit -c unlimited # coredumps
-          make -j4 check-stage3
-        if: matrix.test-speedcenter
-      - name: Test Speedcenter Benchmarks
-        run: |
-          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
-          export BUILD=$PWD/build PATH=$PWD/build/stage1/bin:$PATH
-          cd tests/bench
-          nix shell .#temci -c temci exec --config speedcenter.yaml --included_blocks fast --runs 1
-        if: matrix.test-speedcenter
-      - name: Check rebootstrap
-        run: |
-          cd build
-          ulimit -c unlimited # coredumps
-          make update-stage0 && make -j4
-        if: matrix.name == 'Linux' && needs.configure.outputs.quick == 'false'
-      - name: CCache stats
-        run: ccache -s
-      - name: Show stacktrace for coredumps
-        if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
-        run: |
-          for c in coredumps/*; do
-            progbin="$(file $c | sed "s/.*execfn: '\([^']*\)'.*/\1/")"
-            echo bt | $GDB/bin/gdb -q $progbin $c || true
-          done
-      - name: Upload coredumps
-        uses: actions/upload-artifact@v3
-        if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
-        with:
-          name: coredumps-${{ matrix.name }}
-          path: |
-            ./coredumps
-            ./build/stage0/bin/lean
-            ./build/stage0/lib/lean/libleanshared.so
-            ./build/stage1/bin/lean
-            ./build/stage1/lib/lean/libleanshared.so
-            ./build/stage2/bin/lean
-            ./build/stage2/lib/lean/libleanshared.so
+      # - name: Build Stage 2
+      #   run: |
+      #     cd build
+      #     ulimit -c unlimited # coredumps
+      #     make -j4 stage2
+      #   if: matrix.test-speedcenter
+      # - name: Check Stage 3
+      #   run: |
+      #     cd build
+      #     ulimit -c unlimited # coredumps
+      #     make -j4 check-stage3
+      #   if: matrix.test-speedcenter
+      # - name: Test Speedcenter Benchmarks
+      #   run: |
+      #     echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
+      #     export BUILD=$PWD/build PATH=$PWD/build/stage1/bin:$PATH
+      #     cd tests/bench
+      #     nix shell .#temci -c temci exec --config speedcenter.yaml --included_blocks fast --runs 1
+      #   if: matrix.test-speedcenter
+      # - name: Check rebootstrap
+      #   run: |
+      #     cd build
+      #     ulimit -c unlimited # coredumps
+      #     make update-stage0 && make -j4
+      #   if: matrix.name == 'Linux' && needs.configure.outputs.quick == 'false'
+      # - name: CCache stats
+      #   run: ccache -s
+      # - name: Show stacktrace for coredumps
+      #   if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
+      #   run: |
+      #     for c in coredumps/*; do
+      #       progbin="$(file $c | sed "s/.*execfn: '\([^']*\)'.*/\1/")"
+      #       echo bt | $GDB/bin/gdb -q $progbin $c || true
+      #     done
+      # - name: Upload coredumps
+      #   uses: actions/upload-artifact@v3
+      #   if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
+      #   with:
+      #     name: coredumps-${{ matrix.name }}
+      #     path: |
+      #       ./coredumps
+      #       ./build/stage0/bin/lean
+      #       ./build/stage0/lib/lean/libleanshared.so
+      #       ./build/stage1/bin/lean
+      #       ./build/stage1/lib/lean/libleanshared.so
+      #       ./build/stage2/bin/lean
+      #       ./build/stage2/lib/lean/libleanshared.so
 
   # This job collects results from all the matrix jobs
   # This can be made the “required” job, instead of listing each
